name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare -b deadlock --single-branch https://github.com/neverlosecc/source2sdk.git repo
          cd repo
          git push -f https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git deadlock
