name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          UP=$(git ls-remote https://github.com/neverlosecc/source2sdk.git deadlock | cut -f1)
          [ "$UP" = "$(git ls-remote https://github.com/${{github.repository}}.git deadlock | cut -f1)" ] && exit 0
          git init --bare r && cd r
          git fetch https://github.com/neverlosecc/source2sdk.git deadlock:deadlock
          git push -f https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git deadlock
